import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ContentTheme from "@/contextheme/ContentTheme";
import Footer from "@/components/Footer";
import Backround from "@/components/Backround";
import './globals.css'
import MoblieSocailIcons from "@/components/MoblieSocailIcons";
'../../public/hero-img/hero3.png'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className} >
        <ContentTheme>
          <Backround />
          <MoblieSocailIcons/>
          <div className="body absolute w-full px-4 sm:px-14 lg:px-32 " >
            <Navbar />
            {children}
            <Footer />
          </div>
        </ContentTheme>
      </body>
    </html>
  );
}
